### Add new users and courses to database
POST http://localhost:8080/api/v1/dashboard/internal/db

### Update users and courses in database
POST https://inno-dashboard.duckdns.org/api/v1/dashboard/internal/db